import numpy as np
x = np.array([10, 20, 30, 40, 50, 60])
print(x)
y=np.array(range(1,8))
print(y)
z=np.array((88,13,3))
print(z)
print(len(z))
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.astype(float))
print(np.array([True, False, False, True]))
print(np.array(["spam", "spam", "bacon", "spam"]))
print(np.arange(0, 10, 2))
print(np.linspace([0,4], [1, 6], 3))